---
- name: Cartisan Commerce Server
  hosts: all
  any_errors_fatal: true
  roles:
    - jdk8
    - gradle
    - role: mysql
      mysql:
        database: cartisan_commerce_test
        user: cartisan
        password: pa$$w0rD
    - firefox

- name: Cartisan Commerce CI
  hosts: modern_commerce_ci_servers
  any_errors_fatal: true
  roles:
    - role: jenkins
      jenkins:
        port: 8000