spring:
    datasource:
        username: cartisan
        password: pa$$w0rD
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
    messages:
        basename: BindingErrorMessages

    data:
        mongodb:
            host: localhost
            port: 27017
            database: cartisan-commerce-log
    mail:
        host: smtp.126.com
        username: stwyhm
        password: pa$$w0rD
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true


#    rabbitmq:
#        host: localhost
#        port: 5672
#        username:
#        password:
#    cache:
#      type: simple
#    redis:
#      database: 0       # Redis数据库索引（默认为0）
#      host: localhost   # Redis服务器地址
#      port: 6379        # Redis服务器连接端口
#      password:         # Redis服务器连接密码（默认为空）
#      pool:
#        max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: 1     # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 8     # 连接池中的最大空闲连接
#        min-idle: 0     # 连接池中的最小空闲连接
#      timeout: 0        # 连接超时时间（毫秒）



application:
    perPageLimit: 10

logging:
  config: classpath:log4j2.xml


