spring:
    datasource:
        password: pa$$w0rD
        testWhileIdle: true
        username: cartisan
        validationQuery: SELECT 1
    jpa:
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
    messages:
        basename: BindingErrorMessages

application:
    perPageLimit: 10
