spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cartisan_commerce_test?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    jpa:
        hibernate:
          ddl-auto: create
server:
  port: 8080

#logging:
#  level:
#    com:
#      cartisan: info